on:
  push:
    branches: main

jobs:
  rendertest:
    runs-on: windows-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::renv
            any::learnr
            any::shiny
            any::rmarkdown
            any::rcmdcheck
            any::rlang
            any::devtools


      - name: Check out repository
        uses: actions/checkout@v3

      - name: Test render of tutorials
        run: Rscript -e 'source("./.github/rscripts/tutorial_action.R")'
